import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:donorlink/Models/Donor.dart';
import 'package:donorlink/Models/Organisation.dart';
import 'package:intl/intl.dart';

import 'Interaction.dart';

class Appointment extends Interaction {
  DateTime? approvalDate;
  DateTime appointmentDate;
  bool approvalStatus;
  String reason;

  Appointment(super.id, super.org, super.donor, this.approvalDate, this.approvalStatus, this.reason, this.appointmentDate);

  factory Appointment.fromFirestore(DocumentSnapshot snapshot, Organisation org, Donor donor){
    final data = snapshot.data() as Map<String, dynamic>;
    Appointment app = Appointment(snapshot.id, org , donor , data['approvalDate'], data['approvalStatus'], data['reason'], data['appointmentDate'].toDate());
    app.setDate(data['date'].toDate());
    return app;
  }

  void setReason(String reason) { /*...*/ }
  String getReason() { /*...*/ return reason; }
  DateTime? getApprovalDate() { /*...*/ return approvalDate; }
  bool getStatus() { /*...*/ return approvalStatus; }
  void setApprovalDate(DateTime date) { /*...*/ }
  String getAppointmentDate() {  
    final DateFormat formatter = DateFormat('yyyy-MM-dd');
    final String formatted = formatter.format(appointmentDate);
    return formatted; 
    }
  void setAppointmentDate(DateTime date) { /*...*/ }
  
  @override
  Map<String, dynamic> toFirestore() {
    Map<String, dynamic> map = super.toFirestore();
    map.addAll({
      //id is autogenerated
      "type": "appointment",
      "appointmentDate": appointmentDate,
      "approvalDate": approvalDate,
      "approvalStatus": approvalStatus,
      "reason": reason
    });
    return map;
  }
  
  @override
  String toString(){
    return "${super.toString()} \nAppointment date: $appointmentDate \nReason: $reason";
  }
  
}

