

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:donorlink/Models/Admin.dart';
import 'package:donorlink/Models/Reviewer.dart';

class Approval{
  String id;
  Admin approver;
  Reviewer reviewer;
  DateTime date;

  Approval(this.id , this.approver, this.reviewer, this.date);

  factory Approval.fromFirestore(DocumentSnapshot snapshot,){
    final data = snapshot.data() as Map<String, dynamic>;
    DateTime approveD = data['date']?.toDate(); 
    return Approval(snapshot.id, data['approver'], data['reviewer'], approveD);
  }

  Map<String, dynamic> toFirestore(){
    return {
      //id is autogenerated
      "reviewer": reviewer,
      "approver": approver,
      "date": date,
    };
  }

  @override
  String toString(){
    return 'Approval{id: $id\n approver: $approver\n reviewer: $reviewer';
  }
  
}