import 'package:cloud_firestore/cloud_firestore.dart';

import 'User.dart';
import 'Organisation.dart';
import 'Donation.dart';
import 'Appointment.dart';
import 'Rating.dart';
import 'Financial.dart';

class Donor extends User {
  int rating;

  Donor({required String id, required String name, required String phone, required String email, required this.rating})
      : super(id, name, phone, email,);


  factory Donor.fromFirestore(DocumentSnapshot snapshot,){
      final data = snapshot.data() as Map<String, dynamic>;
      return Donor(
        id: snapshot.id , name: data['name'], phone: data['phone'], email: data['email'], rating:data[ 'rating'],
      );
    }
  
  Map<String, dynamic> toFirestore() {
    return {
      //id is autogenerated
      if (name != null) "name": name,
      if (phone != null) "phone": phone,
      if (email != null) "email": email,
      if (rating != null) "rating": rating,
    };
  }

  void setRating(int rating) {
    this.rating=rating;
  }
  int getRating() {
    return rating; 
  }

  List<Organisation> getOrganisations() { /*...*/ return []; }
  void donate(Donation donation) { /*...*/ }
  void requestAppointment(Appointment appointment) { /*...*/ }
  void rateOrganisation(Rating rating) { /*...*/ }
  

@override
  String toString(){
  return "Donor "+super.toString()+"\nRating: $rating";
}

    @override
  List<Donation> getDonations() {
    // TODO: implement getDonations
    throw UnimplementedError();
  }
  
  @override
  List<Financial> getFinancials() {
    // TODO: implement getFinancials
    throw UnimplementedError();
  }
}
