import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';
import 'Organisation.dart';


class Financial {
  String location;
  Organisation org;
  String id;
  DateTime date;

  Financial(this.id, this.org, this.date, this.location);

  factory Financial.fromFirestore(DocumentSnapshot snapshot,){
      final data = snapshot.data() as Map<String, dynamic>;
      return Financial(snapshot.id, data['org'], data['date'], data['location']);
  }

  Map<String, dynamic> toFirestore() {
    return {
      //id is autogenerated
      "org": org.id,
      "date": date,
      "location": location
    };
  }

  String getDate() { 
    final DateFormat formatter = DateFormat('yyyy-MM-dd');
    final String formatted = formatter.format(date);
    return formatted;
   }
  void setLocation(String location) { /*...*/ }
  String getLocation() { /*...*/ return location; }
  void setDate(DateTime date) { /*...*/ }
  String getID() { /*...*/ return id; }
  Organisation getOrganisation() { /*...*/ return org; }
}
