
import 'package:intl/intl.dart';
import 'Organisation.dart';
import 'Donor.dart';

abstract class Interaction {
  String id;
  Organisation org;
  Donor donor;
  DateTime date=DateTime.now();

  Interaction(this.id, this.org, this.donor);

  @override
  String toString(){
    return 'Organisation: ${org.name} \nDonor: ${donor.name} \nCreation Date: ${getDate()}';
  }

  Map<String, dynamic> toFirestore(){
    return {
      //id is autogenerated
      "org": org.id,
      "donor": donor.id,
      "date": date,
    };
  }

  void setOrg(Organisation org) { /*...*/ }
  void setDonor(Donor donor) { /*...*/ }
  void setID(int id) { /*...*/ }
  void setDate(DateTime date) { 
    this.date=date; 
    }
  Organisation getOrg() { /*...*/ return org; }
  Donor getDonor() { /*...*/ return donor; }
  String getDate() { 
    final DateFormat formatter = DateFormat('yyyy-MM-dd');
    final String formatted = formatter.format(date);
    return formatted;
   }
  String getID() { /*...*/ return id; }
}
