import 'package:donorlink/Database/database.dart';
import 'package:intl/intl.dart';
import 'Hospital.dart';
import 'Patient.dart';

abstract class Interaction {
  Database db = Database();
  String id;
  Hospital org;
  Patient donor;
  DateTime date = DateTime.now();

  Interaction(this.id, this.org, this.donor);

  @override
  String toString() {
    return 'Organisation: ${org.name} \nDonor: ${donor.name} \nCreation Date: ${getDate()}';
  }

  String info() {
    return '';
  }

  Map<String, dynamic> toFirestore() {
    return {
      //id is autogenerated
      "org": org.id,
      "donor": donor.id,
      "date": date,
    };
  }

  Future<bool> updateInteraction() {
    return db.updateInteraction(this);
  }

  void setOrg(Hospital org) {/*...*/}
  void setDonor(Patient donor) {/*...*/}
  void setID(int id) {/*...*/}
  void setDate(DateTime date) {
    this.date = date;
  }

  Hospital getOrg() {
    /*...*/ return org;
  }

  Patient getDonor() {
    /*...*/ return donor;
  }

  String getDate() {
    final DateFormat formatter = DateFormat('yyyy-MM-dd');
    final String formatted = formatter.format(date);
    return formatted;
  }

  String getID() {
    /*...*/ return id;
  }
}
