import 'package:cloud_firestore/cloud_firestore.dart';

import 'User.dart';
import 'Organisation.dart';
import 'Rating.dart';
import 'Review.dart';
import 'Donation.dart';
import 'Financial.dart';

class Reviewer extends User {
  bool approval;

  Reviewer(String id, String name, String phone, String email, this.approval)
      : super(id, name, phone, email,);

  factory Reviewer.fromFirestore(DocumentSnapshot snapshot,){
      final data = snapshot.data() as Map<String, dynamic>;
      return Reviewer(
        snapshot.id, data['name'], data['phone'], data['email'], data['approval'],
      );
    }
  
  Map<String, dynamic> toFirestore() {
    return {
      //id is autogenerated
      if (name != null) "name": name,
      if (phone != null) "phone": phone,
      if (email != null) "email": email,
      if (approval != null) "approval": approval,
    };
  }


  void setApproval(bool approval) { /*...*/ }
  bool getApproval() { /*...*/ return approval; }
  void reviewOrganisation(Organisation org) { /*...*/ }
  List<Organisation> getOrganisations() { /*...*/ return []; }
  List<Rating> getRatings() { /*...*/ return []; }
  List<Review> getReviews() { /*...*/ return []; }
  
  @override
  List<Donation> getDonations() {
    // TODO: implement getDonations
    throw UnimplementedError();
  }
  
  @override
  List<Financial> getFinancials() {
    // TODO: implement getFinancials
    throw UnimplementedError();
  }
}
