
import 'package:donorlink/Database/Database.dart';
import 'package:donorlink/Models/Organisation.dart';
import 'package:firebase_auth/firebase_auth.dart' as fire;


abstract class User {
  Database db = Database();
  final String id;
  String? name;
  String? phone;
  String email;


  User(this.id, this.name, this.phone, this.email,);

  @override
  String toString(){
    return "Name: $name \nPhone number: $phone \nEmail Address: $email";
  }

  Map<String, dynamic> toFirestore(){
    return {
      //id is autogenerated
      if (name != null) "name": name,
      if (phone != null) "phone": phone,
      "email": email,
    };
  }

  Future<List<Organisation>> getOrganisations() async{ 
    return db.getOrganisations();
  }

  Future<bool> updateUser(){
    return db.addUser(this);
  }

  Future<bool> updateEmail() async {
    fire.User? user = await fire.FirebaseAuth.instance.currentUser;
    await user?.verifyBeforeUpdateEmail("janeq@example.com");
    return true;
  }
  
}
