// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOvasAgL6ivMNlhAMi6MR77V8jBAi6Qqo',
    appId: '1:40717852249:web:8f946e33a9a34d3f319b48',
    messagingSenderId: '40717852249',
    projectId: 'donorlink-948a6',
    authDomain: 'donorlink-948a6.firebaseapp.com',
    storageBucket: 'donorlink-948a6.appspot.com',
    measurementId: 'G-GLNR5KFJND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcCbvrjs3cmYHFQyblKnB0Fpj2WrGHLpQ',
    appId: '1:40717852249:android:3116d22df86d1960319b48',
    messagingSenderId: '40717852249',
    projectId: 'donorlink-948a6',
    storageBucket: 'donorlink-948a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCEg1areXKtAd-U2R0NryTAwreOrKeFYU',
    appId: '1:40717852249:ios:57be064c9ab4274d319b48',
    messagingSenderId: '40717852249',
    projectId: 'donorlink-948a6',
    storageBucket: 'donorlink-948a6.appspot.com',
    iosBundleId: 'com.example.donorlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCEg1areXKtAd-U2R0NryTAwreOrKeFYU',
    appId: '1:40717852249:ios:57be064c9ab4274d319b48',
    messagingSenderId: '40717852249',
    projectId: 'donorlink-948a6',
    storageBucket: 'donorlink-948a6.appspot.com',
    iosBundleId: 'com.example.donorlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOvasAgL6ivMNlhAMi6MR77V8jBAi6Qqo',
    appId: '1:40717852249:web:67daf41c32b8138d319b48',
    messagingSenderId: '40717852249',
    projectId: 'donorlink-948a6',
    authDomain: 'donorlink-948a6.firebaseapp.com',
    storageBucket: 'donorlink-948a6.appspot.com',
    measurementId: 'G-S2HNNCGT4B',
  );
}
