import 'dart:io';
import 'package:flutter/material.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:file_picker/file_picker.dart';
import 'package:donorlink/Models/Financial.dart';
import 'package:donorlink/Models/Organisation.dart';

class AddFinancialPage extends StatefulWidget {
  final Organisation organisation;

  const AddFinancialPage({super.key, required this.organisation});

  @override
  _AddFinancialPageState createState() => _AddFinancialPageState();
}

class _AddFinancialPageState extends State<AddFinancialPage> {
  final _formKey = GlobalKey<FormState>();
  bool _isUploading = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Financial Document'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Center(
                child: ElevatedButton(
                  onPressed: _isUploading ? null : _uploadFile,
                  child: _isUploading ? const CircularProgressIndicator() : const Text('Upload PDF'),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Future<void> _uploadFile() async {
    if (_formKey.currentState!.validate()) {
      setState(() {
        _isUploading = true;
      });

      FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf'],
      );

      if (result != null && result.files.single.path != null) {
        String filePath = result.files.single.path!;
        String fileName = result.files.single.name;

        try {
          Reference storageRef = FirebaseStorage.instance.ref().child('financial_documents/$fileName');
          UploadTask uploadTask = storageRef.putFile(File(filePath));
          TaskSnapshot taskSnapshot = await uploadTask;
          String downloadURL = await taskSnapshot.ref.getDownloadURL();
          final newFinancial = Financial(
            '', // ID will be auto-generated by Firestore
            widget.organisation,
            downloadURL,
          );
          await newFinancial.upload();

          ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Financial Document Added')));
          Navigator.pop(context);
        } catch (error) {
          ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Failed to upload file: $error')));
        } finally {
          setState(() {
            _isUploading = false;
          });
        }
      } else {
        setState(() {
          _isUploading = false;
        });
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('No file selected')));
      }
    }
  }

}
